version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    target-branch: "dependencies"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
