name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Update npm version to latest
        run: npm install -g npm@latest # stop showing warnings about the lockfile
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          STACK_API_KEYS: ${{ secrets.STACK_API_KEYS }}
      - name: "Run build"
        run: npm run build
