name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update npm version to latest
        run: npm install -g npm@latest # stop showing warnings about the lockfile
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          STACK_API_KEYS: ${{ secrets.STACK_API_KEYS }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: "Run build"
        run: npm run build
